# -*- coding: utf-8 -*-
"""5.cohorts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nOwUAxd4H--j6q0cU5xSA8dpZwjTs1ua

## Background


Cohorts analysis provide valuable insights into user behavior and performance over time.
- A cohort is a group of users who share a common characteristic or experience within a specified time frame, such as the month they joined a platform.  
- Analyzing cohorts helps understand user engagement, retention, and the impact of product changes.  
- By tracking cohorts, product analysts can identify trends, evaluate the effectiveness of marketing initiatives, and assess the long-term value of acquired customers.

This approach facilitates a more nuanced understanding of user dynamics, enabling companies to tailor strategies and optimize product experiences based on specific user segments.

Some characteristics of a cohort:
1. The timeline (acquisition date/some particular event etc) defines when should a user be mapped to a cohort.  
2. Various cohort durations can be considered and compared to understand user behaviour and draw insights.  
3. A user is considered as active if it's so specific intervals and hence considered as retained, otherwise churned out.
4. Each cohort duration represents a unique group of users.
"""

!pip install retentioneering

"""# 1. Loading data"""

# import required libraries
from retentioneering import datasets

# load sample user behavior data:
stream = datasets.load_simple_shop()

stream.to_dataframe().head()

"""# 2. Visualizing Cohorts"""

stream.cohorts(
    cohort_start_unit='M',
    cohort_period=(1, 'M'), # parameter defining time window
    average = True #True-average for each cohort period. Default value., False - averages are not calculated.
)

"""## Explanation of above visualization:
- For the users in cohort_period = 0 - cohort_period starts from the first click of the user in specified event. All users who perform action during this period fall into the first cohort (zero period).

# 3. Comparing Cohorts for active users
"""

from retentioneering.tooling.cohorts import Cohorts

cohorts = Cohorts(eventstream=stream)
cohorts.fit(
    cohort_start_unit='M',
    cohort_period=(1, 'M'),
    average=False
    )
cohorts.heatmap()

# Having a look at overall average value across all the cohorts
cohorts.lineplot(width=7, height=5, plot_type='average')

# Having a look at individual cohorts
cohorts.lineplot(width=5, height=5, plot_type='cohorts')

cohorts.lineplot(width=7, height=5, plot_type='all');

# To view individual cohorts, along with the average for all the cohorts
cohorts.lineplot(width=7, height=5, plot_type='all');

